// Common
import Head from 'next/head'
import Image from 'next/image'
// Layout
import InnerContainer from '@layouts/InnerContainer'

const Header = () => (
    <>
        <header className='py-12'>
            <InnerContainer>
                <nav className='flex justify-between items-center'>
                    <div className='flex items-center gap-24'>
                        <div className='relative w-56 h-10'>
                            <Image src='/assets/images/logo-global.png' alt='Mavie global' fill />
                        </div>
                        <ul className='flex items-center gap-12 font-extralight'>
                            <li>Intro</li>
                            <li>About</li>
                        </ul>
                    </div>
                </nav>
            </InnerContainer>
        </header>
    </>
)

const Footer = () => (
    <>
        <footer className=''>
            <InnerContainer>
                <p>Footer</p>
            </InnerContainer>
        </footer>
    </>
)

export default function MainLayout ({ children }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className=''>
                <InnerContainer>
                    { children }
                </InnerContainer>
            </main>
            <Footer />
        </>
    )
}
