// Common
import Head from 'next/head'
import Image from 'next/image'
// Fonts
import localFonts from '@next/font/local'
import InnerContainer from '@layouts/InnerContainer'

const EestiPro = localFonts({
    src: [
        {
            path: '../../../public/assets/fonts/GTEestiProText-UltraLight.woff',
            weight: '200'
        },
        {
            path: '../../../public/assets/fonts/GTEestiProText-Light.woff',
            weight: '300'
        },
        {
            path: '../../../public/assets/fonts/GTEestiProText-Regular.woff',
            weight: '400'
        },
    ],
    variable: '--font-eesti'
})

const Header = () => (
    <>
        <header className={`${EestiPro.variable} font-sans py-12`}>
            <InnerContainer>
                <nav className='flex justify-between items-center'>
                    <div className='flex items-center gap-24'>
                        <div className='relative w-56 h-10'>
                            <Image src='/assets/images/logo-global.png' alt='Mavie global' fill />
                        </div>
                        <ul className='flex items-center gap-12 font-extralight'>
                            <li>Intro</li>
                            <li>About</li>
                        </ul>
                    </div>
                </nav>
            </InnerContainer>
        </header>
    </>
)

const Footer = () => (
    <>
        <footer className={`${EestiPro.variable} font-sans`}>
            <InnerContainer>
                <p>Footer</p>
            </InnerContainer>
        </footer>
    </>
)

export default function MainLayout({ children }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            <main className={`${EestiPro.variable} font-sans`}>
                <InnerContainer>
                    { children }
                </InnerContainer>
            </main>
            <Footer />
        </>
    )
}